install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages( c("survival","ggfortify","readxl","Cairo"))
install.packages('rms')
